name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          # First install pinned runtime/dev dependencies to avoid building
          # heavy wheels during the editable install step.
          pip install -r requirements.txt
          # Now install the project in editable mode so repository packages
          # (like `ml`) are importable in CI.
          pip install -e .

      - name: Debug install
        run: |
          echo "Python:" $(python --version)
          echo "pip:" $(pip --version)
          pip list --format=columns
          python -c "import ml, sys; print('ml import ok =>', ml.__file__)"
      - name: Train tiny model
        run: python -m scripts.train_tiny_model
      - name: Lint
        run: python -m flake8 .
      - name: Tests
        run: pytest -q
